server:
  port: 8585

  #db configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  #spring.jpa.properties.hibernate.dialect=
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  data:
    rest:
      base-path: /api