server:
  port: 8585
  ssl:
    enabled: true # Enable HTTPS support (only accept HTTPS requests)
    key-alias: calibra-app # Alias that identifies the key in the key store
    key-store: classpath:calibra-app-keystore.p12 # Keystore location
    key-store-password: secret # Keystore password
    key-store-type: PKCS12 # Keystore format

#db configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  #spring.jpa.properties.hibernate.dialect=
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED
okta:
  oauth2:
    client-id: 0oae5or24enGGjl7H5d7
    issuer: https://dev-22759349.okta.com/oauth2/default

stripe:
  key:
    secret: 

